# Generated by Django 4.1.7 on 2023-02-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description')),
                ('added_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Added datetime')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cost')),
                ('image', models.URLField(blank=True, verbose_name='Image URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='market.category', verbose_name='Product')),
            ],
        ),
    ]
